### ISSUE TITLE
Dragon Quest - Incorrect .exe

### ISSUE THREAD

**Issue by AnticOwl** [MilkyDeveloper/ReshadeForUWP#10]
When making the .bat with the tool an incorrect name is populated.

```
cd %UserProfile%\ReshadeInjectUWP
cmd /c powershell -windowstyle hidden -Command Start-Process -filepath inject.exe Game.exe; Start-Process -filepath explorer.exe shell:appsFolder\39EA002F.DQXISWW_n746a19ndrrjg!Game
```

Correct .exe is DRAGON QUEST XI S.exe

As the name is composed with blank spaces it needs to be between double quote. Looks like it doesn't works.
Managed to be able to inject ReShade manually starting from the %UserProfile%\ReshadeInjectUWP by typing Inject.exe "DRAGON QUEST XI S.exe" and starting the game.

![Screenshot 2021-01-19 175346](https://user-images.githubusercontent.com/76813232/105066924-88f47280-5a7f-11eb-8154-494521661a94.png)

Hope it helps

**Comment by MilkyDeveloper** [comment]
[Fixed!](https://github.com/MilkyDeveloper/ReshadeForUWP/releases/tag/2.2) It would be awesome if you would tell me if it works.
