### ISSUE TITLE
Having an issue where various .fx fail to compile

### ISSUE THREAD

**Issue by SpicyMelonCrab** [MilkyDeveloper/ReshadeForUWP#12]
Hi there, I am trying to load a preset into Final Fantasy XII: The Zodiac Age using your injector. The preset does load, but I get the following errors...

Some effects failed to compile: cursor.fx depthAlpha.fx liquidLens.fx neoBloom.fx pong.fx trackingRays.fx UnrealLens.fx Unsharp.fx VirtualResolution.fx whitepointFixer.fx

Does anyone know how I can restore this functionality to the injected files?

**Comment by MilkyDeveloper** [comment]
Possibly the preset you're using depends on these shaders, which in turn depend on some info that Reshade would extract from the game but it is not able too. Microsoft Store / Xbox Game Pass apps (aka UWP) apps use DirectX differently than normal, so Reshade cannot get the info. All of these effects have to do with modifying the resolution or creating a custom "dummy" one. Most of these effects look like educational ones (e.g. Virtual Resolution, Pong). I'm afraid this can't be fixed yet, as it's a limitation with Reshade itself.
