### ISSUE TITLE
no reshade ingame button HOME does nothing

### ISSUE THREAD

**Issue by Sentakuu** [MilkyDeveloper/ReshadeForUWP#17]
hello so i have installed reshade using your reshade for uwp the game is called dead by daylight i have the microsoft store edition from xbox gamepass PC and it created the batch file when i run the batch file it showes cmd for 10 seconds then launches the game but no reshade bar on top in game and home button does nothing please i really want it to work can you help me :(

**Comment by MilkyDeveloper** [comment]
Can you try using [this guide](https://framedsc.github.io/ReshadeGuides/reshadeuwp.htm)? If the guide works, It's a problem with this program and I'll fix it.
