### ISSUE TITLE
Depth Buffer not working in Flight Simulator 2020

### ISSUE THREAD

**Issue by FinalLightNL** [MilkyDeveloper/ReshadeForUWP#18]
Hi there,

First of all thankyou, you are making it possible to use reshade in UWP. 
Simply fantastic, but i can't get depth buffer to work.

I tried Gshade for example to bypass that, but it doesn't save my settings at each launch.
While yours does, i'm in a bind here.

Can you somehow bypass it?

**Comment by MilkyDeveloper** [comment]
Download [this file](https://github.com/MilkyDeveloper/ReshadeForUWP/releases/download/2.2/unrestrictedDepthBuffer.dll). Type in `C:\Users\%username%\ReshadeInjectUWP` to the File Explorer address bar and delete `Reshade64.dll`. Copy the file you just downloaded to `C:\Users\%username%\ReshadeInjectUWP` and rename it to `Reshade64.dll`.
