### ISSUE TITLE
optimization for minecrfat W10ED?

### ISSUE THREAD

**Issue by kirilltron** [MilkyDeveloper/ReshadeForUWP#19]
Hi, it seems you have already filmed a video about the Reshade UWP for minecraft W10ED, and in the comments under another video you said that there are some problems with it. Are you planning to optimize Reshade for minecraft in the future and is it even possible?

**Comment by MilkyDeveloper** [comment]
I don't have any plans for this, Minecraft uses a frame host, which makes work even harder. I may experiment with an alternative to shaders soon.
