### ISSUE TITLE
Display name UWP and Executable not correct in batch

### ISSUE THREAD

**Issue by AnticOwl** [MilkyDeveloper/ReshadeForUWP#3]
Hi,

This is an example of issue. Especially for this game (Call of the Sea).

cd %UserProfile%\ReshadeInjectUWP
cmd /c powershell -windowstyle hidden -Command Start-Process -filepath inject.exe COTS.exe; Start-Process -filepath explorer.exe shell:appsFolder\RawFury.CallofTheSeaW10_9s0pnehqffj7t!AppCallOfTheSeaShipping

COTS.exe is incorrect

The display name can be read from the appmanifest.xml residing in the the game folder at the root.

```
<IdentityName="RawFury.CallofTheSeaW10" Publisher="CN=D2074FF2-9F55-45EC-8B69-34E9452DB1E3" Version="0.2.64.0" ProcessorArchitecture="x64" />
  <Properties>
    **<DisplayName>Call of The Sea W10</DisplayName>**
    <PublisherDisplayName>Raw Fury</PublisherDisplayName>
    <Logo>Resources\StoreLogo.png</Logo>
    <Description>ms-resource:AppDescription</Description>
  </Properties>"
```

Also, you can extract the correct executable from the same xml file

```
<Applications>
    <Application Id="AppCallOfTheSeaShipping" **Executable="COTS\Binaries\WinGDK\BlueCode-WinGDK-Shipping.exe**" EntryPoint="Windows.FullTrustApplication">
      <uap:VisualElements DisplayName="ms-resource:AppDisplayName" Square150x150Logo="Resources\Logo.png" Square44x44Logo="Resources\SmallLogo.png" Description="ms-resource:AppDescription" ForegroundText="dark" BackgroundColor="#000040">
        <uap:SplashScreen Image="Resources\SplashScreen.png" />
      </uap:VisualElements>
```

As you based your tool on my guide, some credit would have been appreciate ;-)

But anyway, nice work.

**Comment by MilkyDeveloper** [comment]
I see what happened here. Basically I'm using a Regex to extract the string, ```/(Application Id=")+\w+"/gi```. It doesn't necessarily work with special characters, only words, given the fact that the name stopped parsing after the backslash. This new Regex string should work: ```Executable="[^"]*```. Commiting a fix in a few minutes, thanks for the github issue. I didn't know you wrote the guide, I just saw it on the FrameDSC website.

**Comment by MilkyDeveloper** [comment]
C#'s ```System.Diagnostics``` was harder than I thought, so it took some time to make it. Anyways, here's the [release](https://github.com/MilkyDeveloper/ReshadeForUWP/releases/tag/2.1) and be sure to follow the new tutorial on the ```readme.md```.
