### ISSUE TITLE
Failed to allocate and write 'LoadLibrary' argument in target application!

### ISSUE THREAD

**Issue by flobrenge** [MilkyDeveloper/ReshadeForUWP#4]
Trying to use this with Gears 5 from Game Pass and I was able to create the batch using the latest release you have provided but it doesn't manage to inject properly.

```
Waiting for a 'Gears5.exe' process to spawn ...
Found a matching process with PID 11408! Injecting ReShade ...
Failed to allocate and write 'LoadLibrary' argument in target application!
```

As a side note, the exe name that was detected was GearGame.exe but that process is never found, so I corrected it to Gears5.exe which does get found but produces the above error.

**Comment by MilkyDeveloper** [comment]
This is really odd. I guess i'll need to download Gears to see what's up. It look's like this is happening because Gears has [EAC](https://support.gearsofwar.com/hc/en-us/articles/360032905412-Easy-Anti-Cheat) and this injects the DLL externally(**?**).

**Comment by MilkyDeveloper** [comment]
Closing for now because i'm not really sure how to bypass EAC; and plus i'll be liable for getting banned. Sorry about this.
