### ISSUE TITLE
Dragon Quest XIS not injecting

### ISSUE THREAD

**Issue by MikeKostaras** [MilkyDeveloper/ReshadeForUWP#5]
have you done any testing on this game? attempted to inject with the injector but it does not put reshade into the game no matter what

**Comment by AnticOwl** [comment]
Check if the game is not memory protected first. Like Forza.

in Powershell: 

- Type get-apppakage
- Coppy the path of the game (ususally c:\program files\...)
- Press Win+R and paste the path
- Check the folder

If not memory protected, check if the executable in the .bat file is the correct one.

**Comment by MikeKostaras** [comment]
it is correct and it might be write protected but it just does not inject

**Comment by MilkyDeveloper** [comment]
Alright, I know what's up with DQXIS. Basically my Regex doesn't know what to do with ```\```` in the executable name, so what I've done is scrap that entirely. Now all you have to do is theoretically launch the game and select the process in the menu of the app. Committing the new code in a few hours.

**Comment by MikeKostaras** [comment]
sounds good thanks

**Comment by MilkyDeveloper** [comment]
C#'s ```System.Diagnostics``` was harder than I thought, so it took some time to make it. Anyways, here's the [release](https://github.com/MilkyDeveloper/ReshadeForUWP/releases/tag/2.1) and be sure to follow the new tutorial on the ```readme.md```.

**Comment by MilkyDeveloper** [comment]
@MikeKostaras Sorry about this necro but is it working?

**Comment by MikeKostaras** [comment]
Not when I tested it

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
