### ISSUE TITLE
UPDATE versione to 4.9

### ISSUE THREAD

**Issue by ALEMORESCHI** [MilkyDeveloper/ReshadeForUWP#7]
Hi, I saw that the reshade version used is very old, is there a way to update it to 4.9?

**Comment by MilkyDeveloper** [comment]
Sure! Just press ```Win``` ```R``` and type in ```%userprofile%```. Once the explorer window is open, delete the folder ```ReshadeInjectUWP```. After that, just set it up again through the program. Be wary to use the latest version of it though.

Basically this retrieves the Reshade64 DLL from [here](https://github.com/MilkyDeveloper/dump/releases/tag/%E2%99%BE). The ```ReShade64.dll``` file is downloaded from there. Basically I just downloaded the ```ReShade_Setup_X.X.X.exe``` file and opened it with WinRar / 7zip. You'll find a ```ReShade64.dll``` in there. I'll periodically update

**Comment by ALEMORESCHI** [comment]
Thank you. now it's updated!

**Comment by thombomb2009** [comment]
hi I've been trying to do this it lets me select the game but as soon as I click a game when it says launch and done filling everything out and crashes

**Comment by drowhunter** [comment]
Does this even work?  the site it downloads from is version 4 not 5.6

**Comment by ZachFett** [comment]
Is there a way to change it to the newer version of Reshade that has add-on support?
